Dec-09 23:55:43.144 [main] DEBUG nextflow.cli.Launcher - $> nextflow run workflows/mtbcore.nf
Dec-09 23:55:43.433 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.04.4
Dec-09 23:55:43.503 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/odette/.nextflow/plugins; core-plugins: nf-amazon@1.16.2,nf-azure@1.0.1,nf-codecommit@0.1.4,nf-console@1.0.5,nf-ga4gh@1.0.5,nf-google@1.7.3-patch1,nf-tower@1.5.12,nf-wave@0.8.4
Dec-09 23:55:43.525 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Dec-09 23:55:43.528 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Dec-09 23:55:43.543 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Dec-09 23:55:43.566 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Dec-09 23:55:43.615 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /home/odette/mbtCore/nextflow.config
Dec-09 23:55:43.617 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/odette/mbtCore/nextflow.config
Dec-09 23:55:43.661 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Dec-09 23:55:44.939 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 by global default
Dec-09 23:55:44.982 [main] INFO  nextflow.cli.CmdRun - Launching `workflows/mtbcore.nf` [furious_pauling] DSL2 - revision: 5fdbcbd7ad
Dec-09 23:55:44.983 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Dec-09 23:55:44.983 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Dec-09 23:55:45.022 [main] DEBUG nextflow.secret.LocalSecretsProvider - Secrets store: /home/odette/.nextflow/secrets/store.json
Dec-09 23:55:45.041 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@61ab89b0] - activable => nextflow.secret.LocalSecretsProvider@61ab89b0
Dec-09 23:55:45.251 [main] DEBUG nextflow.Session - Session UUID: 04f3df44-286f-40f6-9a99-629c7702d424
Dec-09 23:55:45.252 [main] DEBUG nextflow.Session - Run name: furious_pauling
Dec-09 23:55:45.253 [main] DEBUG nextflow.Session - Executor pool size: 4
Dec-09 23:55:45.280 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=12; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Dec-09 23:55:45.335 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 23.04.4 build 5881
  Created: 25-09-2023 15:34 UTC (18:34 EAST)
  System: Linux 6.2.0-37-generic
  Runtime: Groovy 3.0.16 on OpenJDK 64-Bit Server VM 11.0.1+13-LTS
  Encoding: UTF-8 (UTF-8)
  Process: 229510@Odette [127.0.1.1]
  CPUs: 4 - Mem: 7.6 GB (135.8 MB) - Swap: 2 GB (0)
Dec-09 23:55:45.379 [main] DEBUG nextflow.Session - Work-dir: /home/odette/mbtCore/work [ext2/ext3]
Dec-09 23:55:45.380 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /home/odette/mbtCore/workflows/bin
Dec-09 23:55:45.404 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Dec-09 23:55:45.434 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Dec-09 23:55:45.484 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Dec-09 23:55:45.510 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 5; maxThreads: 1000
Dec-09 23:55:45.750 [main] DEBUG nextflow.Session - Session start
Dec-09 23:55:46.661 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Dec-09 23:55:46.721 [main] INFO  nextflow.Nextflow - 
M T B - NF P I P E L I N E 

Dec-09 23:55:47.804 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Dec-09 23:55:47.805 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Dec-09 23:55:47.821 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Dec-09 23:55:47.829 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=4; memory=7.6 GB; capacity=4; pollInterval=100ms; dumpInterval=5m
Dec-09 23:55:48.050 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Dec-09 23:55:48.051 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Dec-09 23:55:48.084 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Dec-09 23:55:48.086 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Dec-09 23:55:48.100 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: FASTQC, CREATINGDICTFILE, INDEX
Dec-09 23:55:48.101 [main] DEBUG nextflow.Session - Igniting dataflow network (4)
Dec-09 23:55:48.113 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > INDEX
Dec-09 23:55:48.121 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > CREATINGDICTFILE
Dec-09 23:55:48.123 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > FASTQC
Dec-09 23:55:48.124 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Dec-09 23:55:48.124 [main] DEBUG nextflow.Session - Session await
Dec-09 23:55:48.127 [PathVisitor-1] DEBUG nextflow.file.PathVisitor - files for syntax: glob; folder: /home/odette/mbtCore/data/; pattern: *_{1,2}.*; options: [checkIfExists:true]
Dec-09 23:55:48.462 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=CREATINGDICTFILE; work-dir=null
  error [nextflow.exception.ProcessUnrecoverableException]: Process `CREATINGDICTFILE` script contains error(s)
Dec-09 23:55:48.563 [Actor Thread 1] ERROR nextflow.processor.TaskProcessor - Error executing process > 'CREATINGDICTFILE'

Caused by:
  No such variable: ref_file -- Check script 'workflows/../modules/index/indexing.nf' at line: 24

Source block:
  """
      gatk CreateSequenceDictionary -R ${genome} -O ${ref_file.baseName}.dict
      """

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
Dec-09 23:55:48.584 [Actor Thread 1] DEBUG nextflow.Session - Session aborted -- Cause: Process `CREATINGDICTFILE` script contains error(s)
Dec-09 23:55:48.666 [Actor Thread 1] DEBUG nextflow.Session - The following nodes are still active:
[process] INDEX
  status=ACTIVE
  port 0: (value) bound ; channel: genome
  port 1: (cntrl) -     ; channel: $

[process] CREATINGDICTFILE
  status=ACTIVE
  port 0: (value) bound ; channel: genome
  port 1: (cntrl) -     ; channel: $

[process] FASTQC
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

Dec-09 23:55:48.700 [main] DEBUG nextflow.Session - Session await > all processes finished
Dec-09 23:55:48.701 [main] DEBUG nextflow.Session - Session await > all barriers passed
Dec-09 23:55:48.720 [Actor Thread 4] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=CREATINGDICTFILE; work-dir=null
  error [java.lang.InterruptedException]: java.lang.InterruptedException
Dec-09 23:55:48.723 [Actor Thread 8] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=FASTQC; work-dir=null
  error [java.lang.InterruptedException]: java.lang.InterruptedException
Dec-09 23:55:48.727 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=12; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=0; peakCpus=0; peakMemory=0; ]
Dec-09 23:55:48.814 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Dec-09 23:55:48.963 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
